version: "3"

tasks:
  build:
    cmds:
      - go build ./...

  test:
    cmds:
      - go test ./...

  lint:
    cmds:
      - golangci-lint run ./...

  security:
    cmds:
      - go tool govulncheck ./...

  check:
    cmds:
      - test -z "$(gofumpt -l .)"
      - go mod tidy
      - git diff --exit-code -- go.mod go.sum
      - go build ./...
      - go vet ./...
      - golangci-lint run ./...
      - CGO_ENABLED=1 go test -race -shuffle=on ./...
      - go tool govulncheck ./...
